### ISSUE TITLE
Error running filter pandoc-annotate-codeblocks: Exception: unknown tag: Figure

### ISSUE THREAD

**Issue by numero-744** [entangled/entangled#110]
Hello,

I am back to my literate hardware description experiments. It seems to be broken (trying on a commit I am sure was okay).

Might be related to a `panflute` update? Here is the dump:

```
pandoc --filter=pandoc-annotate-codeblocks figures/.cat.md -o **********************.pdf -s -N --template **** --citeproc
Traceback (most recent call last):
  File "/home/****/.local/bin/pandoc-annotate-codeblocks", line 8, in <module>
    sys.exit(main())
  File "/home/****/.local/lib/python3.10/site-packages/entangled/annotate.py", line 24, in main
    return run_filter(action, prepare=prepare)
  File "/home/****/.local/lib/python3.10/site-packages/panflute/io.py", line 260, in run_filter
    return run_filters([action], *args, **kwargs)
  File "/home/****/.local/lib/python3.10/site-packages/panflute/io.py", line 233, in run_filters
    doc = load(input_stream=input_stream)
  File "/home/****/.local/lib/python3.10/site-packages/panflute/io.py", line 56, in load
    doc = json.load(input_stream, object_pairs_hook=from_json)
  File "/usr/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.10/json/__init__.py", line 359, in loads
    return cls(**kw).decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
  File "/home/****/.local/lib/python3.10/site-packages/panflute/elements.py", line 1478, in from_json
    raise Exception('unknown tag: ' + tag)
Exception: unknown tag: Figure
Error running filter pandoc-annotate-codeblocks:
Filter returned error status 1
make: *** [Makefile:61: **********************.pdf] Error 83
```

Edit: `grep` tells me that there is no `Figure` in the markdown source file :thinking:

**Comment by numero-744** [comment]
Closing as a duplicate of https://github.com/entangled/filters/issues/13
